export interface CategoryGroup {
  id: string;
  name: string;
  description: string;
  icon: string;
  categories: string[];
}

export const CATEGORY_GROUPS: CategoryGroup[] = [
  {
    id: "actions",
    name: "Actions & Buttons",
    description: "Interactive triggers with physics-based feedback.",
    icon: "zap",
    categories: [
      "button",
      "loading-button",
      "magnetic",
      "toggle",
      "floating-action",
      "share-menu",
      "copy-button",
      "magnetic-button",
    ],
  },
  {
    id: "inputs",
    name: "Forms & Inputs",
    description: "Modern, validation-ready data collection components.",
    icon: "input",
    categories: [
      "input",
      "textarea",
      "select",
      "multi-select",
      "radio-group",
      "checkbox",
      "switch",
      "slider",
      "otp-input",
      "password-meter",
      "date-picker",
      "date-range-picker",
      "combobox",
      "aurora-input",
      "auth-form",
      "form",
      "search",
      "color-picker",
      "signature-pad",
      "captcha",
      "rating",
    ],
  },
  {
    id: "navigation",
    name: "Navigation",
    description: "Fluid and intuitive wayfinding systems.",
    icon: "navigation",
    categories: [
      "navbar",
      "sidebar",
      "dock",
      "dock-menu",
      "dock-navigation",
      "tabs",
      "breadcrumbs",
      "pagination",
      "stepper",
      "command-palette",
      "scroll-spy",
      "scroll-to-top",
      "footer",
    ],
  },
  {
    id: "feedback",
    name: "Feedback & Loaders",
    description: "State indicators and real-time status pulses.",
    icon: "alert",
    categories: [
      "alert",
      "toast",
      "notification",
      "skeleton",
      "loader",
      "progress-bar",
      "circular-progress",
      "gauge",
      "empty-state",
      "error-boundary",
    ],
  },
  {
    id: "data",
    name: "Data Display",
    description: "High-density information layout components.",
    icon: "grid",
    categories: [
      "card",
      "tilt-card",
      "product-card",
      "pricing-cards",
      "bento-grid",
      "table",
      "data-table",
      "heatmap-table",
      "stats",
      "analog-clock",
      "calendar",
      "timeline",
      "tree-view",
      "tree-map",
      "tech-tree",
      "kbd",
      "badge",
      "qr-code",
    ],
  },
  {
    id: "visualization",
    name: "Visualization",
    description: "Interactive graphs and complex data structures.",
    icon: "line-chart",
    categories: [
      "chart",
      "gantt-chart",
      "node-graph",
      "globe",
      "heatmap",
      "tag-sphere",
      "floorplan-viewer",
    ],
  },
  {
    id: "visual-effects",
    name: "Visual Effects",
    description: "Cinematic backgrounds and sensory animations.",
    icon: "sparkles",
    categories: [
      "particle-bg",
      "aurora-background",
      "spotlight",
      "text-effects",
      "cursor-effects",
      "scroll-animation",
      "confetti",
      "effects",
      "marquee",
      "ticker-tape",
      "typewriter",
      "gradient-border",
    ],
  },
  {
    id: "overlays",
    name: "Overlays & Layout",
    description: "Contextual layers and structural containers.",
    icon: "layers",
    categories: [
      "modal",
      "dialog",
      "drawer",
      "sheet",
      "popover",
      "tooltip",
      "context-menu",
      "dropdown-menu",
      "collapsible",
      "accordion",
      "resizable",
      "separator",
      "aspect-ratio",
      "scroll-area",
    ],
  },
  {
    id: "media",
    name: "Media & Lab",
    description: "Advanced audio, video, and experimental controls.",
    icon: "play",
    categories: [
      "audio-player",
      "audio-eq",
      "frequency-equalizer",
      "video-controls",
      "gallery",
      "image-cropper",
      "magnifier",
      "virtual-joystick",
      "before-after",
      "coverflow",
      "hero-slider",
      "carousel",
      "animated-carousel",
    ],
  },
];

export const getGroupByCategory = (category: string): CategoryGroup | undefined => {
  return CATEGORY_GROUPS.find((group) =>
    group.categories.includes(category.toLowerCase())
  );
};
